dist: trusty
sudo: true
language: python
matrix:
  include:
    - env: TARGET=check2 IMAGE=ubuntu:xenial
    #- env: TARGET=check3 IMAGE=ubuntu-daily:bionic
    #- python: 3.6
    #  env: TARGET=lint
    #- python: 3.4
    #  env: TARGET=coverage
    #  before_script:
    #    - python3 -m pip install -U coverage
    #    - python3 -m pip install -U codecov
    #  script:
    #    - make $TARGET
    #  after_success:
    #    - codecov
# XXX cache the installs?
env:
  global:
    - TRIAL_ARGS=-j4
install:
  - pip install flake8
  # These match "make depends"
  - pip install twisted==16.4.0 mock==1.3.0 configobj==5.0.6 pycurl
  - pip install http://launchpad.net/python-distutils-extra/trunk/2.39/+download/python-distutils-extra-2.39.tar.gz
  # build & install python-apt
  - make -f Makefile.travis pipinstallpythonapt
script:
   - if [ ! -z ${IMAGE} ]; then
      sudo apt-get -y -t trusty-backports install lxd;
      sudo lxd init --auto;
      sudo usermod -a -G lxd travis;
   fi
  - if [ ! -z ${IMAGE} ]; then
      sudo su travis -c 'lxc launch ${IMAGE} testcontainer';
      sudo su travis -c 'lxc config device add testcontainer disk path=/target source='$(pwd);
      sudo su travis -c 'lxc exec testcontainer -- sh -c "cd /target; make ${TARGET}"';
    else
      make $TARGET PYTHON=python$TRAVIS_PYTHON_VERSION'
    fi
